/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useLayoutEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader, useFrame, } from '@react-three/fiber';
import { TextureLoader, MathUtils } from 'three';
import { Vector2 } from 'three';

export function Orb(props) {
  const { nodes, materials } = useGLTF('/orb/orb.gltf')

  const [daymapT, nightmapT, moonT, iconBTC, orb_albedo, orb_emissive, orb_normal, orb_roughness] = useLoader(TextureLoader, [
    '8k_earth_daymap.jpeg',
    '8k_earth_nightmap.jpeg',
    '8k_moon.jpeg',
    'BTC-icon.png',
    'orb/orb_albedo.png',
    'orb/orb_emissive.png',
    'orb/orb_normal.png',
    'orb/orb_roughness.png',
  ]);

  useLayoutEffect(() => {
    // materials[""].color.set('#ff315e') 
    // materials[''].metalness = 0.5
    // materials[''].lightMapIntensity = 0.2
    //materials[''].map = orb_albedo;
    // materials[''].roughnessMap = orb_roughness;
    // materials[''].roughness = 0
    // materials[''].normalMap = orb_normal;
    // materials[''].emissiveMap = orb_emissive;
    console.log("materials ", materials);
    console.log("nodes ", nodes);
  }, [materials])

  useLayoutEffect(() => {
    // materials[""].color.set('#ff315e') 
    // materials[''].metalness = 0.5
    // materials[''].lightMapIntensity = 0.2
    nodes.Sphere_Sphere001.material.map = orb_albedo;
    // materials[''].roughnessMap = orb_roughness;
    // materials[''].roughness = 0
    // materials[''].normalMap = orb_normal;
    // materials[''].emissiveMap = orb_emissive;
    console.log("materials ", materials);
    console.log("nodes ", nodes);
  }, [nodes])

  return (
    <group {...props} dispose={null} scale={0.12}>
      <mesh geometry={nodes.Sphere_Sphere001.geometry} material={nodes.Sphere_Sphere001.material} >
        {/* <meshStandardMaterial map={orb_albedo} normalMap={orb_normal} roughnessMap={orb_roughness} emissiveMap={orb_emissive} /> */}
      </mesh>
    </group>
  )
}

useGLTF.preload('/orb/orb.gltf')
useGLTF.preload('/orb/orb_albedo.png')
useGLTF.preload('/orb/orb_emissive.png')
useGLTF.preload('/orb/orb_normal.png')
useGLTF.preload('/orb/orb_roughness.png')

