/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/orb2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.logo_v4.geometry} material={nodes.logo_v4.material} />
    </group>
  )
}

useGLTF.preload('/orb2.gltf')
